preload = /home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/portrait-skyline.png
preload = /home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/train.jpg
preload = /home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/Cloudsnight.jpg

wallpaper = DP-2,/home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/portrait-skyline.png
wallpaper = HDMI-A-1,/home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/train.jpg
wallpaper = DP-1,/home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/Cloudsnight.jpg

ipc = off
