preload = /home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/an_anubis_with_a_fan.jpg
preload = /home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/portrait-skyline.png
preload = /home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/astronaut.png

wallpaper = DP-2,/home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/portrait-skyline.png
wallpaper = HDMI-A-1,/home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/astronaut.png
wallpaper = DP-1,/home/pundrew/.dotfiles/wallpapers/.local/share/wallpapers/an_anubis_with_a_fan.jpg

ipc = off
